path='C:\\Bench\\CodeHub\\Codeforces\\'
contest_id_one='"id":'
problem_one='problemindex='
problem_index_left='"'
problem_index_right='"'
problem_name_left='<div class="title">'
problem_name_right='</div>'
file_forbidden_chars='<>:"/\\|?*'
message_not_responding='Codeforces not responding, retrying now!'
message_enter_contest_number='Enter the contest number:'
message_contest_does_not_exist='Contest doesn\'t exist\n'
url_contest_list='https://codeforces.com/api/contest.list'
url_contest_left='https://codeforces.com/contest/'
url_contest_right='/problems'
code_cpp='#include <bits/stdc++.h>\n\nusing namespace std;\n\nint main()\n{\n    \n    return 0;\n}\n'
code_cb1='<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>\n<CodeBlocks_project_file>\n	<FileVersion major="1" minor="6" />\n	<Project>\n		<Option title="'
code_cb2='" />\n		<Option pch_mode="2" />\n		<Option compiler="gcc" />\n		<Build>\n			<Target title="Debug">\n				<Option output="bin/Debug/'
code_cb3='" prefix_auto="1" extension_auto="1" />\n				<Option object_output="obj/Debug/" />\n				<Option type="1" />\n				<Option compiler="gcc" />\n				<Compiler>\n					<Add option="-std=c++11" />\n					<Add option="-g" />\n				</Compiler>\n			</Target>\n			<Target title="Release">\n				<Option output="bin/Release/'
code_cb4='" prefix_auto="1" extension_auto="1" />\n				<Option object_output="obj/Release/" />\n				<Option type="1" />\n				<Option compiler="gcc" />\n				<Compiler>\n					<Add option="-O2" />\n				</Compiler>\n				<Linker>\n					<Add option="-s" />\n				</Linker>\n			</Target>\n		</Build>\n		<Compiler>\n			<Add option="-Wall" />\n			<Add option="-fexceptions" />\n		</Compiler>\n		<Unit filename="main.cpp" />\n		<Extensions>\n			<code_completion />\n			<envvars />\n			<debugger />\n		</Extensions>\n	</Project>\n</CodeBlocks_project_file>\n'
