tp_main='main'
tp_bf='bf'
tp_ch='ch'
tp_gen='gen'
tps=[tp_main,tp_bf,tp_ch,tp_gen]
ctp_num='num'
ctp_str='str'
verdict_wa='WA'

help_contest='contest'
help_problem='problem'

problem_one='problemindex='
problem_index_left='"'
problem_index_right='"'
problem_name_left='<div class="title">'
problem_name_right='</div>'
test_left='<pre>'
test_right='</pre>'
test_newline='<br />'
test_smaller_than='&lt;'
test_greater_than='&gt;'
allowed_chars='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789 '
