tp_main='main'
tp_bf='bf'
tp_ch='ch'
tp_gen='gen'
tps=[tp_main,tp_bf,tp_ch,tp_gen]
verdict_wa='WA'
comm_code='code'
comm_codeall='codeall'
comm_debug='debug'
comm_add='add'
comm_keep='keep'
comm_rm='rm'
comm_tl='tl'
comm_stress='stress'
comm_check='check'
comm_path='path'
comm_cls='cls'
comm_help='help'
comm_exit='exit'
comms=[comm_code,comm_codeall,comm_debug,comm_add,comm_keep,comm_rm,comm_tl,comm_stress,comm_check,comm_path,comm_cls,comm_help,comm_exit]
comms_args={
    comm_code:2,
    comm_codeall:0,
    comm_debug:2,
    comm_add:1,
    comm_keep:2,
    comm_rm:2,
    comm_tl:2,
    comm_stress:2,
    comm_check:2,
    comm_path:0,
    comm_cls:0,
    comm_help:0,
    comm_exit:0
}
help_contest='contest'
help_problem='problem'

problem_one='problemindex='
problem_index_left='"'
problem_index_right='"'
problem_name_left='<div class="title">'
problem_name_right='</div>'
test_left='<pre>'
test_right='</pre>'
test_newline='<br />'
test_smaller_than='&lt;'
test_greater_than='&gt;'
allowed_chars='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789 '
